import Head from "next/head";
import About from "../components/About";
import Main from "../components/Main";
import Navbar from "../components/Navbar";
import { design } from "../constants/design";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Nijhum | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${design.paddingX} ${design.flexCenter}`}>
        <div className={`${design.boxWidth}`}>
          <Navbar />
        </div>
      </div>
      <div className={`${design.flexCenter}`}>
        <div className={`${design.boxWidth}`}>
          <Main />
        </div>
      </div>
      <div className={`${design.paddingX} ${design.flexCenter}`}>
        <div className={`${design.boxWidth}`}>
          <About />
        </div>
      </div>
    </div>
  );
};

export default Home;
