import Head from "next/head";
import Navbar from "../components/Navbar";
import { styles } from "../constants";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Nijhum | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.paddingX} ${styles.flexCenter}`}>
        <div className={`${styles.boxWidth}`}>
          <Navbar />
        </div>
      </div>
      <div className={`${styles.paddingX} ${styles.flexCenter}`}>
        <div className={`${styles.boxWidth}`}></div>
      </div>
    </div>
  );
}
